//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plany
{
    using System;
    using System.Collections.Generic;
    
    public partial class kierunek
    {
        public decimal id_kierunek { get; set; }
        public string wydzial { get; set; }
        public string nazwa { get; set; }
    }
}
