//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanyEntities3 : DbContext
    {
        public PlanyEntities3()
            : base("name=PlanyEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<katedra> katedra { get; set; }
        public virtual DbSet<przedmiot> przedmiot { get; set; }
        public virtual DbSet<specjalnosc> specjalnosc { get; set; }
        public virtual DbSet<kierunek> kierunek { get; set; }
        public virtual DbSet<studenci> studenci { get; set; }
        public virtual DbSet<pracownicy> pracownicy { get; set; }
        public virtual DbSet<stypendium> stypendium { get; set; }
    }
}
