//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plany
{
    using System;
    using System.Collections.Generic;
    
    public partial class pracownicy
    {
        public decimal id_pracownik { get; set; }
        public Nullable<decimal> id_wykladowcy { get; set; }
        public Nullable<decimal> id_katedra { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<short> obecnosc_dzieci { get; set; }
        public Nullable<decimal> ile_dzieci { get; set; }
        public string plec { get; set; }
        public Nullable<int> pokój { get; set; }
        public string stopien { get; set; }
        public string kategoria { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public string czy_wykladowca { get; set; }
        public Nullable<int> rok_urodzenia { get; set; }
    }
}
