//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plany
{
    using System;
    using System.Collections.Generic;
    
    public partial class studenci
    {
        public decimal id_studenci { get; set; }
        public Nullable<decimal> id_katedra { get; set; }
        public Nullable<decimal> id_stypendum { get; set; }
        public decimal id_specjalnosc { get; set; }
        public decimal id_kierunek { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<short> obecnosc_dzieci { get; set; }
        public Nullable<int> ile_dzieci { get; set; }
        public string plec { get; set; }
        public string grupa { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public Nullable<int> rok_urodzenia { get; set; }
    }
}
